# Generated by Django 5.0.3 on 2024-03-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0003_remove_product_image_remove_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
