# Generated by Django 5.0.2 on 2024-03-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0005_remove_product_category_product_image_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gymApp.category'),
        ),
    ]
